server:
  port: 8080

spring:
  application:
    name: ExternalService
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${server.port}


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
    level:
       root: INFO
