server:
  port: 8082

spring:
  application:
    name: InternalService
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${server.port}

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  logging:
    level: DEBUG
